package main_pack;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class tic_tac_toe extends javax.swing.JFrame {

    /**
     * Creates new form tic_tac_toe
     */
    public tic_tac_toe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        score_1 = new javax.swing.JLabel();
        score_2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setPreferredSize(new java.awt.Dimension(650, 450));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jb1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jb1.setPreferredSize(new java.awt.Dimension(33, 33));
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jb2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jb3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        jb4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });

        jb5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });

        jb6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });

        jb7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });

        jb8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });

        jb9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 90, 310, 260);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 130, 130, 40);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 130, 130, 40);

        score_1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        score_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score_1.setText("0");
        score_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(score_1);
        score_1.setBounds(20, 200, 100, 40);

        score_2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        score_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score_2.setText("0");
        score_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(score_2);
        score_2.setBounds(480, 200, 100, 40);

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 350, 140, 40);

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 350, 140, 40);

        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton3.setText("New Game");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 350, 140, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 130, 90);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(444, 24, 130, 90);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("1");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 30, 100, 40);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Round");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 30, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int start = 0;
int rounds = 1;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
String a = JOptionPane.showInputDialog(null,"Enter Player 1 Name:-");
String b = JOptionPane.showInputDialog(null,"Enter Player 2 Name:-");
jLabel1.setText(a);
jLabel2.setText(b);
img_Set();
    }//GEN-LAST:event_formWindowOpened

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
turn(jb1);
boolean b = check();
if(b == true)
{
JOptionPane.showMessageDialog(null,"Game Ended");
img_Set();
score();
player_Switch();
next_Round();
set_Null();
start = 0;
}
else if(b == false && not_empty_check() == true)
{
JOptionPane.showMessageDialog(null, "Good Game, It was a Draw.");
player_Switch();
next_Round();
img_Set();
set_Null();
}
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
      turn(jb2);
boolean b = check();
if(b == true)
{
JOptionPane.showMessageDialog(null,"Game Ended");
img_Set();
score();
next_Round();
set_Null();
player_Switch();
start = 0;
}
else if(b == false && not_empty_check() == true)
{
JOptionPane.showMessageDialog(null, "Good Game, It was a Draw.");
img_Set();
next_Round();
player_Switch();
set_Null();
}
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
 turn(jb3);
boolean b = check();
if(b == true)
{
JOptionPane.showMessageDialog(null,"Game Ended");
score();
next_Round();
img_Set();
set_Null();
player_Switch();
start = 0;
}
else if(b == false && not_empty_check() == true)
{
JOptionPane.showMessageDialog(null, "Good Game, It was a Draw.");
img_Set();
next_Round();
player_Switch();
set_Null();
}
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
    turn(jb4);
boolean b = check();
if(b == true)
{
JOptionPane.showMessageDialog(null,"Game Ended");
img_Set();
next_Round();
player_Switch();
score();
set_Null();

start = 0;
}
else if(b == false && not_empty_check() == true)
{
JOptionPane.showMessageDialog(null, "Good Game, It was a Draw.");
img_Set();
next_Round();
player_Switch();
set_Null();
}
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
     turn(jb5);
boolean b = check();
if(b == true)
{
JOptionPane.showMessageDialog(null,"Game Ended");
img_Set();
next_Round();
player_Switch();
score();
set_Null();

start = 0;
}
else if(b == false && not_empty_check() == true)
{
JOptionPane.showMessageDialog(null, "Good Game, It was a Draw.");
img_Set();
next_Round();
player_Switch();
set_Null();
}
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
   turn(jb6);
boolean b = check();
if(b == true)
{
JOptionPane.showMessageDialog(null,"Game Ended");
img_Set();
next_Round();
player_Switch();
score();
set_Null();

start = 0;
}
else if(b == false && not_empty_check() == true)
{
JOptionPane.showMessageDialog(null, "Good Game, It was a Draw.");
img_Set();
next_Round();
player_Switch();
set_Null();
}
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
   turn(jb7);
boolean b = check();
if(b == true)
{
JOptionPane.showMessageDialog(null,"Game Ended");
img_Set();
next_Round();
player_Switch();
score();
set_Null();

start = 0;
}
else if(b == false && not_empty_check() == true)
{
JOptionPane.showMessageDialog(null, "Good Game, It was a Draw.");
img_Set();
next_Round();
player_Switch();
set_Null();
}
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
     turn(jb8);
boolean b = check();
if(b == true)
{
JOptionPane.showMessageDialog(null,"Game Ended");
img_Set();
next_Round();
player_Switch();
score();
set_Null();

start = 0;
}
else if(b == false && not_empty_check() == true)
{
JOptionPane.showMessageDialog(null, "Good Game, It was a Draw.");
img_Set();
next_Round();
player_Switch();
set_Null();
}
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
    turn(jb9);
boolean b = check();
if(b == true)
{
JOptionPane.showMessageDialog(null,"Game Ended");
img_Set();
next_Round();
player_Switch();
score();
set_Null();

start = 0;
}
else if(b == false && not_empty_check() == true)
{
JOptionPane.showMessageDialog(null, "Good Game, It was a Draw.");
img_Set();
next_Round();
player_Switch();
set_Null();
}
    }//GEN-LAST:event_jb9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
set_Null();
start = 0;
img_Set();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String a = JOptionPane.showInputDialog(null,"Enter Player 1 Name:-");
String b = JOptionPane.showInputDialog(null,"Enter Player 2 Name:-");
jLabel1.setText(a);
jLabel2.setText(b);
jLabel5.setText("1");
start = 0;
img_Set();
score_1.setText("0");
score_2.setText("0");
set_Null();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tic_tac_toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tic_tac_toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tic_tac_toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tic_tac_toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tic_tac_toe().setVisible(true);
            }
        });
    }
public boolean check()
{
String []s = {jb1.getText(),jb2.getText(),jb3.getText(),
              jb4.getText(),jb5.getText(),jb6.getText(),
              jb7.getText(),jb8.getText(),jb9.getText(),};
boolean b = false;
if(s[0] == s[1] && s[0] == s[2] && s[0].isEmpty() == false)
    b = true;
else if (s[3] == s[4] && s[3] == s[5] && s[3].isEmpty() == false)
    b = true;
else if (s[6] == s[7] && s[6] == s[8] && s[6].isEmpty() == false)
    b = true;
else if (s[0] == s[3] && s[0] == s[6] && s[0].isEmpty() == false)
    b = true;
else if (s[1] == s[4] && s[1] == s[7] && s[1].isEmpty() == false)
    b = true;
else if (s[2] == s[5] && s[2] == s[8] && s[2].isEmpty() == false)
    b = true;
else if (s[0] == s[4] && s[0] == s[8] && s[0].isEmpty() == false)
    b = true;
else if (s[2] == s[4] && s[2] == s[6] && s[2].isEmpty() == false)
    b = true;

else 
{
    b = false;
        }
return b;
}
public void turn(JButton j)
{
if(j.getText().isEmpty() == true)
{
if(start == 0)
{
j.setText("X");
jLabel4.setIcon(new ImageIcon(getClass().getResource("arrow.png")));
jLabel3.setIcon(null);
start = 1;
}
else if(start == 1)
{
j.setText("O");
jLabel3.setIcon(new ImageIcon(getClass().getResource("arrow.png")));
jLabel4.setIcon(null);
start = 0;
}
}
}
public boolean not_empty_check()
{
    String []s = {jb1.getText(),jb2.getText(),jb3.getText(),
              jb4.getText(),jb5.getText(),jb6.getText(),
              jb7.getText(),jb8.getText(),jb9.getText(),};
boolean a = false;
if(s[0].isEmpty() == false && s[1].isEmpty() == false && s[2].isEmpty() == false &&
        s[3].isEmpty() == false && s[4].isEmpty() == false && s[5].isEmpty() == false && 
        s[6].isEmpty() == false && s[7].isEmpty() == false && s[8].isEmpty() == false)
{
a = true;
}
return a;
}
public void score()

{
int one = Integer.parseInt(score_1.getText());
int two = Integer.parseInt(score_2.getText());
if(start == 1)
{
++one;
score_1.setText(""+one);
}
else if(start == 0)
{
++two;
score_2.setText(""+two);
}
}

public void set_Null()
{
JButton []j = {jb1,jb2,jb3,jb4,jb5,jb6,jb7,jb8,jb9};
int i = 0;
while(i<=8)
{
j[i].setText("");
++i;
}
}
public void player_Switch()
{
String n1 = jLabel1.getText();
String n2 = jLabel2.getText();
String s1 = score_1.getText();
String s2 = score_2.getText();
jLabel1.setText(n2);
jLabel2.setText(n1);
score_1.setText(s2);
score_2.setText(s1);
start = 0;
}

public void img_Set()
{
jLabel3.setIcon(new ImageIcon(getClass().getResource("arrow.png")));
jLabel4.setIcon(null);
}
public void next_Round()
{
rounds++;
jLabel5.setText(""+ rounds);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JLabel score_1;
    private javax.swing.JLabel score_2;
    // End of variables declaration//GEN-END:variables
}
